language: c
compiler: 
  - gcc
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3
    packages:
      - cmake
      - cmake-data
script:
  - mkdir build && cd build
  - cmake ..
  - make
sudo: false
